/**
 * Searchable item type for component search index
 */
export interface SearchableItem {
  text: string;
  sectionId: string;
  subsectionTitle?: string;
  type: 'section' | 'subsection' | 'button' | 'label' | 'checkbox' | 'radio' | 'switch' | 'slider' | 'badge' | 'alert' | 'toast' | 'tooltip' | 'breadcrumb' | 'tab' | 'divider' | 'menu' | 'icon' | 'component';
}

export const UI_SEARCH_INDEX: SearchableItem[] = [
  // Buttons section
  { text: 'Buttons', sectionId: 'buttons', type: 'section' },
  { text: 'Button', sectionId: 'buttons', type: 'button' },
  { text: 'Button Variants', sectionId: 'buttons', subsectionTitle: 'Button Variants', type: 'subsection' },
  { text: 'Primary', sectionId: 'buttons', type: 'button' },
  { text: 'Secondary', sectionId: 'buttons', type: 'button' },
  { text: 'Outline', sectionId: 'buttons', type: 'button' },
  { text: 'Ghost', sectionId: 'buttons', type: 'button' },
  { text: 'Disabled', sectionId: 'buttons', type: 'button' },
  { text: 'Button Sizes', sectionId: 'buttons', subsectionTitle: 'Button Sizes', type: 'subsection' },
  { text: 'Small', sectionId: 'buttons', type: 'button' },
  { text: 'Medium', sectionId: 'buttons', type: 'button' },
  { text: 'Large', sectionId: 'buttons', type: 'button' },
  { text: 'Button with Icon', sectionId: 'buttons', subsectionTitle: 'Button with Icon', type: 'subsection' },
  { text: 'Download', sectionId: 'buttons', type: 'button' },
  { text: 'Copy', sectionId: 'buttons', type: 'button' },
  { text: 'Settings', sectionId: 'buttons', type: 'button' },
  { text: 'Icon Only', sectionId: 'buttons', type: 'button' },
  { text: 'Loading State', sectionId: 'buttons', subsectionTitle: 'Loading State', type: 'subsection' },
  { text: 'Loading', sectionId: 'buttons', type: 'button' },
  { text: 'Spinner', sectionId: 'buttons', type: 'button' },
  { text: 'Copy Button', sectionId: 'buttons', subsectionTitle: 'Copy Button', type: 'subsection' },
  { text: 'Copy Text', sectionId: 'buttons', type: 'button' },
  { text: 'Copy Code', sectionId: 'buttons', type: 'button' },
  { text: 'Full Width', sectionId: 'buttons', subsectionTitle: 'Full Width', type: 'subsection' },
  { text: 'Full Width Button', sectionId: 'buttons', type: 'button' },
  { text: 'Polymorphic Rendering', sectionId: 'buttons', subsectionTitle: 'Polymorphic Rendering', type: 'subsection' },
  { text: 'Link Button', sectionId: 'buttons', type: 'button' },
  { text: 'External Link', sectionId: 'buttons', type: 'button' },

  // Cards section
  { text: 'Cards', sectionId: 'cards', type: 'section' },
  { text: 'Card', sectionId: 'cards', type: 'button' },
  { text: 'Card Variants', sectionId: 'cards', subsectionTitle: 'Card Variants', type: 'subsection' },
  { text: 'Default', sectionId: 'cards', type: 'button' },
  { text: 'Dark', sectionId: 'cards', type: 'button' },
  { text: 'Raised', sectionId: 'cards', type: 'button' },
  { text: 'Card with Sub-components', sectionId: 'cards', subsectionTitle: 'Card with Sub-components', type: 'subsection' },
  { text: 'Card without Padding', sectionId: 'cards', subsectionTitle: 'Card without Padding', type: 'subsection' },

  // Forms section
  { text: 'Forms', sectionId: 'forms', type: 'section' },
  { text: 'Input', sectionId: 'forms', type: 'button' },
  { text: 'Input Sizes', sectionId: 'forms', subsectionTitle: 'Input Sizes', type: 'subsection' },
  { text: 'Input States', sectionId: 'forms', subsectionTitle: 'Input States', type: 'subsection' },
  { text: 'Input with Icon', sectionId: 'forms', subsectionTitle: 'Input with Icon', type: 'subsection' },
  { text: 'TextArea', sectionId: 'forms', type: 'button' },
  { text: 'Label', sectionId: 'forms', type: 'button' },
  { text: 'Select', sectionId: 'forms', type: 'button' },
  { text: 'Checkbox', sectionId: 'forms', type: 'checkbox' },
  { text: 'Radio', sectionId: 'forms', type: 'radio' },
  { text: 'RadioGroup', sectionId: 'forms', type: 'radio' },
  { text: 'Switch', sectionId: 'forms', type: 'switch' },
  { text: 'Switch Sizes', sectionId: 'forms', subsectionTitle: 'Switch Sizes', type: 'subsection' },
  { text: 'Switch States', sectionId: 'forms', subsectionTitle: 'Switch States', type: 'subsection' },
  { text: 'Slider', sectionId: 'forms', type: 'slider' },
  { text: 'Slider Sizes', sectionId: 'forms', subsectionTitle: 'Slider Sizes', type: 'subsection' },
  { text: 'Slider with Label & Value', sectionId: 'forms', subsectionTitle: 'Slider with Label & Value', type: 'subsection' },
  { text: 'Combobox', sectionId: 'forms', type: 'component' },
  { text: 'Combobox with Custom Value', sectionId: 'forms', subsectionTitle: 'Combobox with Custom Value', type: 'subsection' },
  { text: 'Combobox States', sectionId: 'forms', subsectionTitle: 'Combobox States', type: 'subsection' },
  { text: 'Autocomplete', sectionId: 'forms', type: 'component' },
  { text: 'NumberField', sectionId: 'forms', type: 'component' },
  { text: 'NumberField Sizes', sectionId: 'forms', subsectionTitle: 'NumberField Sizes', type: 'subsection' },
  { text: 'NumberField States', sectionId: 'forms', subsectionTitle: 'NumberField States', type: 'subsection' },
  { text: 'NumberField with Formatting', sectionId: 'forms', subsectionTitle: 'NumberField with Formatting', type: 'subsection' },

  // Feedback section
  { text: 'Feedback', sectionId: 'feedback', type: 'section' },
  { text: 'Badge', sectionId: 'feedback', type: 'badge' },
  { text: 'Badge Variants', sectionId: 'feedback', subsectionTitle: 'Badge Variants', type: 'subsection' },
  { text: 'Badge Sizes', sectionId: 'feedback', subsectionTitle: 'Badge Sizes', type: 'subsection' },
  { text: 'Badge with Icon & Click', sectionId: 'feedback', subsectionTitle: 'Badge with Icon & Click', type: 'subsection' },
  { text: 'BadgeGroup', sectionId: 'feedback', type: 'badge' },
  { text: 'Alert', sectionId: 'feedback', type: 'alert' },
  { text: 'Alert Variants', sectionId: 'feedback', subsectionTitle: 'Alert Variants', type: 'subsection' },
  { text: 'Alert with Title', sectionId: 'feedback', subsectionTitle: 'Alert with Title', type: 'subsection' },
  { text: 'Closable Alert', sectionId: 'feedback', subsectionTitle: 'Closable Alert', type: 'subsection' },
  { text: 'Progress', sectionId: 'feedback', type: 'component' },
  { text: 'Progress Variants', sectionId: 'feedback', subsectionTitle: 'Progress Variants', type: 'subsection' },
  { text: 'Progress Sizes', sectionId: 'feedback', subsectionTitle: 'Progress Sizes', type: 'subsection' },
  { text: 'Progress with Label', sectionId: 'feedback', subsectionTitle: 'Progress with Label', type: 'subsection' },
  { text: 'Spinner', sectionId: 'feedback', type: 'component' },
  { text: 'Skeleton', sectionId: 'feedback', type: 'component' },
  { text: 'Skeleton Variants', sectionId: 'feedback', subsectionTitle: 'Skeleton Variants', type: 'subsection' },
  { text: 'Skeleton Loading State', sectionId: 'feedback', subsectionTitle: 'Skeleton Loading State', type: 'subsection' },
  { text: 'Tooltip', sectionId: 'feedback', type: 'tooltip' },
  { text: 'Tooltip Positions', sectionId: 'feedback', subsectionTitle: 'Tooltip Positions', type: 'subsection' },
  { text: 'Tooltip Sizes', sectionId: 'feedback', subsectionTitle: 'Tooltip Sizes', type: 'subsection' },
  { text: 'Tooltip with Delay', sectionId: 'feedback', subsectionTitle: 'Tooltip with Delay', type: 'subsection' },
  { text: 'Toast', sectionId: 'feedback', type: 'toast' },
  { text: 'ToastProvider', sectionId: 'feedback', type: 'toast' },

  // Data display section
  { text: 'Data display', sectionId: 'data-display', type: 'section' },
  { text: 'Avatar', sectionId: 'data-display', type: 'component' },
  { text: 'Avatar Sizes', sectionId: 'data-display', subsectionTitle: 'Avatar Sizes', type: 'subsection' },
  { text: 'Avatar Variants', sectionId: 'data-display', subsectionTitle: 'Avatar Variants', type: 'subsection' },
  { text: 'Avatar with Image', sectionId: 'data-display', subsectionTitle: 'Avatar with Image', type: 'subsection' },
  { text: 'Table', sectionId: 'data-display', type: 'component' },
  { text: 'Table with Sub-components', sectionId: 'data-display', subsectionTitle: 'Table with Sub-components', type: 'subsection' },
  { text: 'Table Row States', sectionId: 'data-display', subsectionTitle: 'Table Row States', type: 'subsection' },

  // Navigation section
  { text: 'Navigation', sectionId: 'navigation', type: 'section' },
  { text: 'Tabs', sectionId: 'navigation', type: 'tab' },
  { text: 'Tabs Variants', sectionId: 'navigation', subsectionTitle: 'Tabs Variants', type: 'subsection' },
  { text: 'Tabs with Icons', sectionId: 'navigation', subsectionTitle: 'Tabs with Icons', type: 'subsection' },
  { text: 'Tabs Orientation', sectionId: 'navigation', subsectionTitle: 'Tabs Orientation', type: 'subsection' },
  { text: 'Pill', sectionId: 'navigation', type: 'tab' },
  { text: 'Manila', sectionId: 'navigation', type: 'tab' },
  { text: 'Divider', sectionId: 'navigation', type: 'divider' },
  { text: 'Divider Variants', sectionId: 'navigation', subsectionTitle: 'Divider Variants', type: 'subsection' },
  { text: 'Divider Orientation', sectionId: 'navigation', subsectionTitle: 'Divider Orientation', type: 'subsection' },
  { text: 'Solid', sectionId: 'navigation', type: 'divider' },
  { text: 'Dashed', sectionId: 'navigation', type: 'divider' },
  { text: 'Decorated', sectionId: 'navigation', type: 'divider' },
  { text: 'Accordion', sectionId: 'navigation', type: 'component' },
  { text: 'Accordion Single', sectionId: 'navigation', subsectionTitle: 'Accordion Single', type: 'subsection' },
  { text: 'Accordion Multiple', sectionId: 'navigation', subsectionTitle: 'Accordion Multiple', type: 'subsection' },
  { text: 'Breadcrumbs', sectionId: 'navigation', type: 'breadcrumb' },
  { text: 'Breadcrumbs Separator', sectionId: 'navigation', subsectionTitle: 'Breadcrumbs Separator', type: 'subsection' },

  // Overlays section
  { text: 'Overlays', sectionId: 'overlays', type: 'section' },
  { text: 'Dialog', sectionId: 'overlays', type: 'menu' },
  { text: 'Sheet', sectionId: 'overlays', type: 'menu' },
  { text: 'Sheet Sides', sectionId: 'overlays', subsectionTitle: 'Sheet Sides', type: 'subsection' },
  { text: 'Sheet with Footer', sectionId: 'overlays', subsectionTitle: 'Sheet with Footer', type: 'subsection' },
  { text: 'Popover', sectionId: 'overlays', type: 'menu' },
  { text: 'Popover Positions', sectionId: 'overlays', subsectionTitle: 'Popover Positions', type: 'subsection' },
  { text: 'DropdownMenu', sectionId: 'overlays', type: 'menu' },
  { text: 'DropdownMenu Positions', sectionId: 'overlays', subsectionTitle: 'DropdownMenu Positions', type: 'subsection' },
  { text: 'ContextMenu', sectionId: 'overlays', type: 'menu' },
  { text: 'HelpPanel', sectionId: 'overlays', type: 'component' },

  // Layout section
  { text: 'Layout', sectionId: 'layout', type: 'section' },
  { text: 'ScrollArea', sectionId: 'layout', type: 'component' },
  { text: 'ScrollArea Horizontal', sectionId: 'layout', subsectionTitle: 'ScrollArea Horizontal', type: 'subsection' },
  { text: 'ScrollArea Hidden Scrollbar', sectionId: 'layout', subsectionTitle: 'ScrollArea Hidden Scrollbar', type: 'subsection' },
];
