import type { SearchableItem } from './DesignSystemTab';

export const UI_SEARCH_INDEX: SearchableItem[] = [
  // Buttons section
  { text: 'Buttons', sectionId: 'buttons', type: 'section' },
  { text: 'Button', sectionId: 'buttons', type: 'button' },
  { text: 'Button Variants', sectionId: 'buttons', subsectionTitle: 'Button Variants', type: 'subsection' },
  { text: 'Primary', sectionId: 'buttons', type: 'button' },
  { text: 'Secondary', sectionId: 'buttons', type: 'button' },
  { text: 'Outline', sectionId: 'buttons', type: 'button' },
  { text: 'Ghost', sectionId: 'buttons', type: 'button' },
  { text: 'Button Sizes', sectionId: 'buttons', subsectionTitle: 'Button Sizes', type: 'subsection' },
  { text: 'Sm', sectionId: 'buttons', type: 'button' },
  { text: 'Md', sectionId: 'buttons', type: 'button' },
  { text: 'Lg', sectionId: 'buttons', type: 'button' },

  // Cards section
  { text: 'Cards', sectionId: 'cards', type: 'section' },
  { text: 'Card', sectionId: 'cards', type: 'button' },
  { text: 'Card Variants', sectionId: 'cards', subsectionTitle: 'Card Variants', type: 'subsection' },
  { text: 'Default', sectionId: 'cards', type: 'button' },
  { text: 'Dark', sectionId: 'cards', type: 'button' },
  { text: 'Raised', sectionId: 'cards', type: 'button' },
  { text: 'Card with Sub-components', sectionId: 'cards', subsectionTitle: 'Card with Sub-components', type: 'subsection' },

  // Forms section
  { text: 'Forms', sectionId: 'forms', type: 'section' },
  { text: 'Input', sectionId: 'forms', type: 'button' },
  { text: 'Input Sizes', sectionId: 'forms', subsectionTitle: 'Input Sizes', type: 'subsection' },
  { text: 'Sm', sectionId: 'forms', type: 'button' },
  { text: 'Md', sectionId: 'forms', type: 'button' },
  { text: 'Lg', sectionId: 'forms', type: 'button' },
  { text: 'TextArea', sectionId: 'forms', type: 'button' },
  { text: 'Label', sectionId: 'forms', type: 'button' },
  { text: 'Select', sectionId: 'forms', type: 'button' },
  { text: 'Checkbox', sectionId: 'forms', type: 'button' },
  { text: 'Radio', sectionId: 'forms', type: 'button' },
  { text: 'RadioGroup', sectionId: 'forms', type: 'button' },
  { text: 'Switch', sectionId: 'forms', type: 'button' },
  { text: 'Switch Sizes', sectionId: 'forms', subsectionTitle: 'Switch Sizes', type: 'subsection' },
  { text: 'Sm', sectionId: 'forms', type: 'button' },
  { text: 'Md', sectionId: 'forms', type: 'button' },
  { text: 'Lg', sectionId: 'forms', type: 'button' },
  { text: 'Slider', sectionId: 'forms', type: 'button' },
  { text: 'Slider Sizes', sectionId: 'forms', subsectionTitle: 'Slider Sizes', type: 'subsection' },
  { text: 'Sm', sectionId: 'forms', type: 'button' },
  { text: 'Md', sectionId: 'forms', type: 'button' },
  { text: 'Lg', sectionId: 'forms', type: 'button' },

  // Feedback section
  { text: 'Feedback', sectionId: 'feedback', type: 'section' },
  { text: 'Badge', sectionId: 'feedback', type: 'button' },
  { text: 'Badge Variants', sectionId: 'feedback', subsectionTitle: 'Badge Variants', type: 'subsection' },
  { text: 'Default', sectionId: 'feedback', type: 'button' },
  { text: 'Success', sectionId: 'feedback', type: 'button' },
  { text: 'Warning', sectionId: 'feedback', type: 'button' },
  { text: 'Error', sectionId: 'feedback', type: 'button' },
  { text: 'Info', sectionId: 'feedback', type: 'button' },
  { text: 'Badge Sizes', sectionId: 'feedback', subsectionTitle: 'Badge Sizes', type: 'subsection' },
  { text: 'Sm', sectionId: 'feedback', type: 'button' },
  { text: 'Md', sectionId: 'feedback', type: 'button' },
  { text: 'Progress', sectionId: 'feedback', type: 'button' },
  { text: 'Progress Variants', sectionId: 'feedback', subsectionTitle: 'Progress Variants', type: 'subsection' },
  { text: 'Default', sectionId: 'feedback', type: 'button' },
  { text: 'Success', sectionId: 'feedback', type: 'button' },
  { text: 'Warning', sectionId: 'feedback', type: 'button' },
  { text: 'Error', sectionId: 'feedback', type: 'button' },
  { text: 'Progress Sizes', sectionId: 'feedback', subsectionTitle: 'Progress Sizes', type: 'subsection' },
  { text: 'Sm', sectionId: 'feedback', type: 'button' },
  { text: 'Md', sectionId: 'feedback', type: 'button' },
  { text: 'Lg', sectionId: 'feedback', type: 'button' },
  { text: 'Spinner', sectionId: 'feedback', type: 'button' },
  { text: 'Skeleton', sectionId: 'feedback', type: 'button' },
  { text: 'Skeleton Variants', sectionId: 'feedback', subsectionTitle: 'Skeleton Variants', type: 'subsection' },
  { text: 'Text', sectionId: 'feedback', type: 'button' },
  { text: 'Circular', sectionId: 'feedback', type: 'button' },
  { text: 'Rectangular', sectionId: 'feedback', type: 'button' },
  { text: 'Tooltip', sectionId: 'feedback', type: 'button' },
  { text: 'Tooltip Sizes', sectionId: 'feedback', subsectionTitle: 'Tooltip Sizes', type: 'subsection' },
  { text: 'Sm', sectionId: 'feedback', type: 'button' },
  { text: 'Md', sectionId: 'feedback', type: 'button' },
  { text: 'Lg', sectionId: 'feedback', type: 'button' },
  { text: 'Alert', sectionId: 'feedback', type: 'button' },
  { text: 'Alert Variants', sectionId: 'feedback', subsectionTitle: 'Alert Variants', type: 'subsection' },
  { text: 'Default', sectionId: 'feedback', type: 'button' },
  { text: 'Success', sectionId: 'feedback', type: 'button' },
  { text: 'Warning', sectionId: 'feedback', type: 'button' },
  { text: 'Error', sectionId: 'feedback', type: 'button' },
  { text: 'Info', sectionId: 'feedback', type: 'button' },
  { text: 'ToastProvider', sectionId: 'feedback', type: 'button' },

  // Data display section
  { text: 'Data display', sectionId: 'data-display', type: 'section' },
  { text: 'Avatar', sectionId: 'data-display', type: 'button' },
  { text: 'Avatar Variants', sectionId: 'data-display', subsectionTitle: 'Avatar Variants', type: 'subsection' },
  { text: 'Circle', sectionId: 'data-display', type: 'button' },
  { text: 'Square', sectionId: 'data-display', type: 'button' },
  { text: 'Avatar Sizes', sectionId: 'data-display', subsectionTitle: 'Avatar Sizes', type: 'subsection' },
  { text: 'Sm', sectionId: 'data-display', type: 'button' },
  { text: 'Md', sectionId: 'data-display', type: 'button' },
  { text: 'Lg', sectionId: 'data-display', type: 'button' },
  { text: 'Xl', sectionId: 'data-display', type: 'button' },
  { text: 'Table', sectionId: 'data-display', type: 'button' },
  { text: 'Table with Sub-components', sectionId: 'data-display', subsectionTitle: 'Table with Sub-components', type: 'subsection' },

  // Navigation section
  { text: 'Navigation', sectionId: 'navigation', type: 'section' },
  { text: 'Tabs', sectionId: 'navigation', type: 'button' },
  { text: 'Tabs Variants', sectionId: 'navigation', subsectionTitle: 'Tabs Variants', type: 'subsection' },
  { text: 'Pill', sectionId: 'navigation', type: 'button' },
  { text: 'Line', sectionId: 'navigation', type: 'button' },
  { text: 'Tabs with Sub-components', sectionId: 'navigation', subsectionTitle: 'Tabs with Sub-components', type: 'subsection' },
  { text: 'Divider', sectionId: 'navigation', type: 'button' },
  { text: 'Divider Variants', sectionId: 'navigation', subsectionTitle: 'Divider Variants', type: 'subsection' },
  { text: 'Solid', sectionId: 'navigation', type: 'button' },
  { text: 'Dashed', sectionId: 'navigation', type: 'button' },
  { text: 'Decorated', sectionId: 'navigation', type: 'button' },
  { text: 'Accordion', sectionId: 'navigation', type: 'button' },
  { text: 'Accordion with Sub-components', sectionId: 'navigation', subsectionTitle: 'Accordion with Sub-components', type: 'subsection' },
  { text: 'Breadcrumbs', sectionId: 'navigation', type: 'button' },

  // Overlays section
  { text: 'Overlays', sectionId: 'overlays', type: 'section' },
  { text: 'Dialog', sectionId: 'overlays', type: 'button' },
  { text: 'Dialog with Sub-components', sectionId: 'overlays', subsectionTitle: 'Dialog with Sub-components', type: 'subsection' },
  { text: 'Sheet', sectionId: 'overlays', type: 'button' },
  { text: 'Sheet with Sub-components', sectionId: 'overlays', subsectionTitle: 'Sheet with Sub-components', type: 'subsection' },
  { text: 'Popover', sectionId: 'overlays', type: 'button' },
  { text: 'Popover with Sub-components', sectionId: 'overlays', subsectionTitle: 'Popover with Sub-components', type: 'subsection' },
  { text: 'DropdownMenu', sectionId: 'overlays', type: 'button' },
  { text: 'DropdownMenu with Sub-components', sectionId: 'overlays', subsectionTitle: 'DropdownMenu with Sub-components', type: 'subsection' },
  { text: 'ContextMenu', sectionId: 'overlays', type: 'button' },
  { text: 'ContextMenu with Sub-components', sectionId: 'overlays', subsectionTitle: 'ContextMenu with Sub-components', type: 'subsection' },
  { text: 'HelpPanel', sectionId: 'overlays', type: 'button' },

];